"""nullable-bong-fields

Revision ID: 2322ebd5de3d
Revises: 61f765d3b1f1
Create Date: 2026-04-28 14:25:26.221888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2322ebd5de3d'
down_revision: Union[str, Sequence[str], None] = '61f765d3b1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bongs', 'tier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bongs', 'score',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               nullable=True)
    op.alter_column('bongs', 'llm_response',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bongs', 'llm_response',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bongs', 'score',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               nullable=False)
    op.alter_column('bongs', 'tier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
